apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivolve-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ivolve-project
  template:
    metadata:
      labels:
        app: ivolve-project
    spec:
      containers:
      - name: jenkins-project
        image: saeedkouta/ivolve-test1:v1
        ports:
        - containerPort: 8080
